[package]
name = "gazer"
version = "0.1.0"
authors = ["rodchenkov-sn <serod2015@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0.14"
clap = {version = "~2.27.0", features = ["yaml"]}
